<?php

declare(strict_types=1);

function seedRolePermissions(PDO $pdo): int
{
    $stmtRole = $pdo->query("SELECT id, name FROM roles");
    $roles = [];
    while ($row = $stmtRole->fetch()) {
        $roles[$row['name']] = (int)$row['id'];
    }

    $stmtPerm = $pdo->query("SELECT id, name FROM permissions");
    $perms = [];
    while ($row = $stmtPerm->fetch()) {
        $perms[$row['name']] = (int)$row['id'];
    }

    $matrix = [
        'SUPER_ADMIN' => [
            'view_farmers', 'manage_farmers',
            'view_centres', 'manage_centres',
            'view_slots', 'manage_slots',
            'view_queue', 'manage_queue',
            'view_procurement', 'manage_procurement',
            'view_payments', 'manage_payments',
            'view_reports',
            'manage_staff',
            'approve_corrections',
            'view_audit_logs',
            'manage_languages',
            'manage_files',
            'manage_system_settings',
            'settings.view',
            'settings.manage',
            'settings.secret_manage',
            'manage_sessions',
            'manage_secrets',
            'manage_maintenance',
            'maintenance.manage',
            'translations.view',
            'translations.manage',
            'files.upload',
            'files.download',
            'files.delete',
            'files.folders',
            'files.manage_all',
            'centres.view',
            'centres.manage',
            'centres.status.manage',
            'staff.view',
            'staff.manage',
            'districts.manage',
            'slots.view',
            'slots.manage',
            'slots.cancel',
            'bookings.create',
            'bookings.view_own',
            'bookings.view_any',
            'bookings.cancel_any',
            'tokens.view_own',
            'tokens.view_any',
            'crops.view',
            'queue.view',
            'queue.view_own',
            'queue.call_next',
            'queue.skip',
            'queue.no_show',
            'queue.stats',
            'procurements.create',
            'procurements.update',
            'procurements.reject',
            'procurements.approve',
            'procurements.view_any',
            'procurements.view_own',
            'payments.view',
            'payments.release',
            'payments.cancel',
            'payments.reverse',
            'rates.manage',
            'notifications.view',
            'notifications.test',
        ],
        'DISTRICT_ADMIN' => [
            'view_farmers', 'manage_farmers',
            'view_centres', 'manage_centres',
            'view_slots', 'manage_slots',
            'view_queue', 'manage_queue',
            'view_procurement', 'manage_procurement',
            'view_payments', 'manage_payments',
            'view_reports',
            'manage_staff',
            'approve_corrections',
            'view_audit_logs',
            'settings.view',
            'manage_sessions',
            'translations.view',
            'translations.manage',
            'files.upload',
            'files.download',
            'files.delete',
            'files.folders',
            'files.manage_all',
            'centres.view',
            'centres.manage',
            'centres.status.manage',
            'staff.view',
            'staff.manage',
            'slots.view',
            'slots.manage',
            'slots.cancel',
            'bookings.view_any',
            'bookings.cancel_any',
            'tokens.view_any',
            'crops.view',
            'queue.view',
            'queue.call_next',
            'queue.skip',
            'queue.no_show',
            'queue.stats',
            'procurements.create',
            'procurements.update',
            'procurements.reject',
            'procurements.approve',
            'procurements.view_any',
            'procurements.view_own',
            'payments.view',
            'payments.release',
            'payments.cancel',
            'payments.reverse',
            'rates.manage',
            'notifications.view',
            'notifications.test',
        ],
        'CENTRE_MANAGER' => [
            'view_farmers', 'manage_farmers',
            'view_centres', 'manage_centres',
            'view_slots', 'manage_slots',
            'view_queue', 'manage_queue',
            'view_procurement', 'manage_procurement',
            'view_payments', 'manage_payments',
            'view_reports',
            'manage_staff',
            'approve_corrections',
            'view_audit_logs',
            'translations.view',
            'files.upload',
            'files.download',
            'files.delete',
            'files.folders',
            'files.manage_all',
            'centres.view',
            'centres.manage',
            'centres.status.manage',
            'slots.view',
            'slots.manage',
            'slots.cancel',
            'bookings.view_any',
            'bookings.cancel_any',
            'tokens.view_any',
            'crops.view',
            'queue.view',
            'queue.call_next',
            'queue.skip',
            'queue.no_show',
            'queue.stats',
            'procurements.create',
            'procurements.update',
            'procurements.reject',
            'procurements.approve',
            'procurements.view_any',
            'procurements.view_own',
            'payments.view',
            'payments.release',
            'payments.cancel',
            'notifications.view',
            'notifications.test',
        ],
        'CENTRE_OPERATOR' => [
            'view_centres',
            'view_slots',
            'view_queue', 'manage_queue',
            'view_procurement', 'manage_procurement',
            'view_payments',
            'view_reports',
            'translations.view',
            'files.upload',
            'files.download',
            'files.delete',
            'files.folders',
            'files.manage_all',
            'centres.view',
            'slots.view',
            'bookings.view_any',
            'tokens.view_any',
            'crops.view',
            'queue.view',
            'queue.call_next',
            'queue.skip',
            'queue.no_show',
            'queue.stats',
            'procurements.create',
            'procurements.update',
            'procurements.reject',
            'procurements.view_any',
            'procurements.view_own',
            'payments.view',
        ],
        'FARMER' => [
            'view_centres',
            'view_slots',
            'view_queue',
            'view_procurement',
            'view_payments',
            'manage_own_profile',
            'book_slot',
            'manage_own_bookings',
            'view_own_queue',
            'view_own_procurement',
            'view_own_payments',
            'translations.view',
            'files.upload',
            'files.download',
            'files.delete',
            'centres.view',
            'slots.view',
            'bookings.create',
            'bookings.view_own',
            'tokens.view_own',
            'crops.view',
            'queue.view',
            'queue.view_own',
            'procurements.view_own',
        ],
    ];

    $count = 0;
    $stmt = $pdo->prepare("INSERT IGNORE INTO role_permissions (role_id, permission_id) VALUES (?, ?)");

    foreach ($matrix as $roleName => $permissionNames) {
        if (!isset($roles[$roleName])) {
            continue;
        }
        $roleId = $roles[$roleName];
        foreach ($permissionNames as $permName) {
            if (!isset($perms[$permName])) {
                continue;
            }
            $stmt->execute([$roleId, $perms[$permName]]);
            if ($stmt->rowCount() > 0) {
                $count++;
            }
        }
    }

    return $count;
}
