<?php

declare(strict_types=1);

return [
    'system_name' => [
        'type' => 'STRING',
        'default' => 'Farmer Procurement System',
        'public' => true,
        'sensitive' => false,
        'group' => 'GENERAL',
        'description' => 'Display name of the system',
    ],
    'default_language' => [
        'type' => 'STRING',
        'default' => 'en',
        'public' => true,
        'sensitive' => false,
        'group' => 'GENERAL',
        'description' => 'Default language code',
    ],
    'timezone' => [
        'type' => 'STRING',
        'default' => 'Asia/Kolkata',
        'public' => true,
        'sensitive' => false,
        'group' => 'GENERAL',
        'description' => 'System timezone',
    ],
    'support_contact_phone' => [
        'type' => 'STRING',
        'default' => '',
        'public' => true,
        'sensitive' => false,
        'group' => 'GENERAL',
        'description' => 'Support phone number',
    ],
    'support_contact_email' => [
        'type' => 'STRING',
        'default' => '',
        'public' => true,
        'sensitive' => false,
        'group' => 'GENERAL',
        'description' => 'Support email address',
    ],

    'maintenance_mode' => [
        'type' => 'BOOL',
        'default' => false,
        'public' => true,
        'sensitive' => false,
        'group' => 'MAINTENANCE',
        'description' => 'Enable maintenance mode',
    ],
    'maintenance_message' => [
        'type' => 'STRING',
        'default' => '',
        'public' => true,
        'sensitive' => false,
        'group' => 'MAINTENANCE',
        'description' => 'Message shown during maintenance',
    ],
    'maintenance_expected_available_at' => [
        'type' => 'STRING',
        'default' => '',
        'public' => true,
        'sensitive' => false,
        'group' => 'MAINTENANCE',
        'description' => 'Expected availability time',
    ],

    'push_enabled' => [
        'type' => 'BOOL',
        'default' => true,
        'public' => false,
        'sensitive' => false,
        'group' => 'NOTIFICATION',
        'description' => 'Enable OneSignal push notifications',
    ],
    'sms_enabled' => [
        'type' => 'BOOL',
        'default' => true,
        'public' => false,
        'sensitive' => false,
        'group' => 'NOTIFICATION',
        'description' => 'Enable SMS notifications (OTP gateway)',
    ],
    'notification_retry_count' => [
        'type' => 'INT',
        'default' => 3,
        'public' => false,
        'sensitive' => false,
        'group' => 'NOTIFICATION',
        'description' => 'Max notification retry attempts',
    ],
    'notification_retry_interval_seconds' => [
        'type' => 'INT',
        'default' => 300,
        'public' => false,
        'sensitive' => false,
        'group' => 'NOTIFICATION',
        'description' => 'Seconds between notification retries',
    ],
    'queue_notification_threshold' => [
        'type' => 'INT',
        'default' => 3,
        'public' => false,
        'sensitive' => false,
        'group' => 'NOTIFICATION',
        'description' => 'Notify farmer when N farmers ahead',
    ],
    'sms_from_name' => [
        'type' => 'STRING',
        'default' => 'FPS',
        'public' => false,
        'sensitive' => false,
        'group' => 'NOTIFICATION',
        'description' => 'SMS sender name',
    ],
    'notification_language_default' => [
        'type' => 'STRING',
        'default' => 'en',
        'public' => false,
        'sensitive' => false,
        'group' => 'NOTIFICATION',
        'description' => 'Default language for notifications',
    ],
    'otp_expiry_minutes' => [
        'type' => 'INT',
        'default' => 5,
        'public' => false,
        'sensitive' => false,
        'group' => 'NOTIFICATION',
        'description' => 'OTP validity in minutes',
    ],
    'otp_resend_cooldown_seconds' => [
        'type' => 'INT',
        'default' => 60,
        'public' => false,
        'sensitive' => false,
        'group' => 'NOTIFICATION',
        'description' => 'Cooldown between OTP resends',
    ],
    'two_factor_enabled_default' => [
        'type' => 'BOOL',
        'default' => false,
        'public' => false,
        'sensitive' => false,
        'group' => 'NOTIFICATION',
        'description' => 'Default 2FA state for new users',
    ],

    'booking_cancellation_window_minutes' => [
        'type' => 'INT',
        'default' => 120,
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'Minutes before slot to allow cancellation',
    ],
    'booking.horizon_days' => [
        'type' => 'INT',
        'default' => 7,
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'Max days ahead a farmer may book',
    ],
    'booking.min_lead_hours' => [
        'type' => 'INT',
        'default' => 2,
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'Minimum hours before slot start to allow booking',
    ],
    'booking.cancel_lead_minutes' => [
        'type' => 'INT',
        'default' => 120,
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'Minutes before slot start to allow cancellation',
    ],
    'booking.max_active' => [
        'type' => 'INT',
        'default' => 1,
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'Maximum active (pending/confirmed) bookings a farmer may hold',
    ],
    'auto_confirm_on_payment' => [
        'type' => 'BOOL',
        'default' => false,
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'If true, confirm booking + issue token immediately; if false, wait for payment success',
    ],
    'max_crops_per_booking' => [
        'type' => 'INT',
        'default' => 10,
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'Maximum crops per booking',
    ],
    'max_quantity_kg_per_booking' => [
        'type' => 'INT',
        'default' => 5000,
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'Maximum total quantity (kg) per booking',
    ],
    'slot.horizon_days' => [
        'type' => 'INT',
        'default' => 7,
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'Number of days ahead to auto-generate slots',
    ],
    'slot.default_duration_minutes' => [
        'type' => 'INT',
        'default' => 15,
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'Default slot duration in minutes',
    ],
    'slot.default_capacity' => [
        'type' => 'INT',
        'default' => 10,
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'Default max tokens per slot',
    ],
    'slot.min_capacity' => [
        'type' => 'INT',
        'default' => 1,
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'Minimum allowed capacity per slot',
    ],
    'slot.breaks' => [
        'type' => 'JSON',
        'default' => [],
        'public' => false,
        'sensitive' => false,
        'group' => 'BOOKING',
        'description' => 'Break ranges excluded during slot generation (e.g. ["12:00-13:00"])',
    ],

    'queue.avg_minutes_per_token' => [
        'type' => 'INT',
        'default' => 10,
        'public' => false,
        'sensitive' => false,
        'group' => 'QUEUE',
        'description' => 'Average minutes per token for ETA estimates',
    ],
    'queue.grace_no_show_minutes' => [
        'type' => 'INT',
        'default' => 5,
        'public' => false,
        'sensitive' => false,
        'group' => 'QUEUE',
        'description' => 'Grace period (minutes) after a call before no-show can be marked',
    ],
    'queue.notify_threshold' => [
        'type' => 'INT',
        'default' => 3,
        'public' => false,
        'sensitive' => false,
        'group' => 'QUEUE',
        'description' => 'Notify farmer when farmers ahead drops to this threshold',
    ],
    'queue.call_batch' => [
        'type' => 'INT',
        'default' => 1,
        'public' => false,
        'sensitive' => false,
        'group' => 'QUEUE',
        'description' => 'Number of farmers served per call-next action',
    ],
    'queue.recall_limit' => [
        'type' => 'INT',
        'default' => 1,
        'public' => false,
        'sensitive' => false,
        'group' => 'QUEUE',
        'description' => 'Maximum times a skipped entry may be recalled to the end of the queue',
    ],

    'procurement.approval_required' => [
        'type' => 'BOOL',
        'default' => true,
        'public' => false,
        'sensitive' => false,
        'group' => 'PROCUREMENT',
        'description' => 'Require manager/district approval after operator capture',
    ],
    'procurement.max_photos' => [
        'type' => 'INT',
        'default' => 3,
        'public' => false,
        'sensitive' => false,
        'group' => 'PROCUREMENT',
        'description' => 'Maximum QC photos per procurement',
    ],
    'procurement.weight_precision' => [
        'type' => 'INT',
        'default' => 2,
        'public' => false,
        'sensitive' => false,
        'group' => 'PROCUREMENT',
        'description' => 'Decimal precision for accepted/damaged weight capture',
    ],

    'payment.allow_operator_release' => [
        'type' => 'BOOL',
        'default' => false,
        'public' => false,
        'sensitive' => false,
        'group' => 'PAYMENTS',
        'description' => 'Allow centre operators to release payments with reference (manager+ by default)',
    ],

    'session_timeout_minutes' => [
        'type' => 'INT',
        'default' => 30,
        'public' => false,
        'sensitive' => false,
        'group' => 'SECURITY',
        'description' => 'Session timeout in minutes',
    ],
    'remember_me_expiry_days' => [
        'type' => 'INT',
        'default' => 30,
        'public' => false,
        'sensitive' => false,
        'group' => 'SECURITY',
        'description' => 'Remember-me token expiry in days',
    ],
    'max_concurrent_sessions' => [
        'type' => 'INT',
        'default' => 10,
        'public' => false,
        'sensitive' => false,
        'group' => 'SECURITY',
        'description' => 'Max concurrent sessions per user',
    ],
    'max_login_attempts' => [
        'type' => 'INT',
        'default' => 5,
        'public' => false,
        'sensitive' => false,
        'group' => 'SECURITY',
        'description' => 'Max failed login attempts before lockout',
    ],
    'lockout_minutes' => [
        'type' => 'INT',
        'default' => 15,
        'public' => false,
        'sensitive' => false,
        'group' => 'SECURITY',
        'description' => 'Lockout duration in minutes',
    ],

    'file_upload_max_size_mb' => [
        'type' => 'INT',
        'default' => 5,
        'public' => false,
        'sensitive' => false,
        'group' => 'FILE',
        'description' => 'Max file upload size in MB',
    ],
    'allowed_file_types' => [
        'type' => 'JSON',
        'default' => ['jpg', 'png', 'pdf'],
        'public' => false,
        'sensitive' => false,
        'group' => 'FILE',
        'description' => 'Allowed file extensions',
    ],

    'rate_limit_login_per_min' => [
        'type' => 'INT',
        'default' => 5,
        'public' => false,
        'sensitive' => false,
        'group' => 'RATE_LIMIT',
        'description' => 'Max login attempts per minute',
    ],
    'rate_limit_otp_per_5min' => [
        'type' => 'INT',
        'default' => 3,
        'public' => false,
        'sensitive' => false,
        'group' => 'RATE_LIMIT',
        'description' => 'Max OTP requests per 5 minutes',
    ],
    'rate_limit_booking_per_min' => [
        'type' => 'INT',
        'default' => 10,
        'public' => false,
        'sensitive' => false,
        'group' => 'RATE_LIMIT',
        'description' => 'Max booking requests per minute',
    ],
    'rate_limit_sms_per_min' => [
        'type' => 'INT',
        'default' => 10,
        'public' => false,
        'sensitive' => false,
        'group' => 'RATE_LIMIT',
        'description' => 'Max SMS sends per minute',
    ],
    'rate_limit_general_per_min' => [
        'type' => 'INT',
        'default' => 60,
        'public' => false,
        'sensitive' => false,
        'group' => 'RATE_LIMIT',
        'description' => 'General rate limit per minute',
    ],
];