<?php

declare(strict_types=1);

return [
    'app.name' => 'Farmer Procurement System',
    'app.tagline' => 'Smooth procurement, transparent payments',
    'app.language' => 'Language',

    'nav.home' => 'Home',
    'nav.dashboard' => 'Dashboard',
    'nav.bookings' => 'Bookings',
    'nav.queue' => 'Queue',
    'nav.procurement' => 'Procurement',
    'nav.payments' => 'Payments',
    'nav.profile' => 'Profile',
    'nav.settings' => 'Settings',
    'nav.admin' => 'Admin',
    'nav.logout' => 'Logout',

    'auth.login' => 'Login',
    'auth.register' => 'Register',
    'auth.mobile' => 'Mobile number',
    'auth.password' => 'Password',
    'auth.otp' => 'OTP',
    'auth.forgot_password' => 'Forgot password?',
    'auth.reset_password' => 'Reset password',
    'auth.welcome_back' => 'Welcome back',
    'auth.login_title' => 'Login to your account',

    'common.save' => 'Save',
    'common.cancel' => 'Cancel',
    'common.confirm' => 'Confirm',
    'common.delete' => 'Delete',
    'common.edit' => 'Edit',
    'common.view' => 'View',
    'common.close' => 'Close',
    'common.search' => 'Search',
    'common.submit' => 'Submit',
    'common.next' => 'Next',
    'common.back' => 'Back',
    'common.ok' => 'OK',
    'common.yes' => 'Yes',
    'common.no' => 'No',
    'common.actions' => 'Actions',
    'common.all' => 'All',
    'common.loading' => 'Loading...',
    'common.language' => 'Language',
    'common.none' => 'None',

    'booking.title' => 'Book a slot',
    'booking.book_slot' => 'Book slot',
    'booking.slot' => 'Slot',
    'booking.date' => 'Date',
    'booking.crops' => 'Crops',
    'booking.cancel' => 'Cancel booking',
    'booking.confirm' => 'Confirm booking',
    'booking.success' => 'Your slot has been booked successfully',

    'queue.title' => 'Live queue',
    'queue.position' => 'Your position',
    'queue.ahead' => 'Farmers ahead of you',
    'queue.status_called' => 'Called',
    'queue.status_waiting' => 'Waiting',

    'procurement.title' => 'Procurement',
    'procurement.gross' => 'Gross weight',
    'procurement.deduction' => 'Deductions',
    'procurement.net' => 'Net weight',
    'procurement.rate' => 'Rate',

    'payment.title' => 'Payments',
    'payment.amount' => 'Amount',
    'payment.status' => 'Status',
    'payment.pending' => 'Pending',
    'payment.paid' => 'Paid',

    'validation.required' => 'This field is required',
    'validation.invalid_mobile' => 'Enter a valid mobile number',
    'validation.invalid_otp' => 'Invalid or expired OTP',

    'errors.generic' => 'Something went wrong',
    'errors.network' => 'No internet connection',
    'errors.forbidden' => 'You do not have permission',
    'errors.not_found' => 'Not found',

    'dashboard.greeting' => 'Hello',
    'dashboard.active_bookings' => 'Active bookings',
    'dashboard.next_slot' => 'Next booking slot',
    'dashboard.balance' => 'Pending payment',

    'settings.language' => 'Language',
    'settings.notification' => 'Notifications',
    'settings.change_password' => 'Change password',
    'settings.notifications_enabled' => 'Enable notifications',

    'files.title' => 'Files',
    'files.upload' => 'Upload',
    'files.download' => 'Download',
    'files.delete' => 'Delete',
    'files.folder' => 'Folder',
    'files.size' => 'Size',
    'files.type' => 'Type',
    'files.uploaded_at' => 'Uploaded at',
    'files.scope' => 'Scope',
    'files.no_files' => 'No files found',
    'files.confirm_delete' => 'Delete this file forever?',

    'internal.admin.tooltip' => 'For administrators only',
];