<?php

declare(strict_types=1);

return [
    'app.name' => 'किसान खरीद प्रणाली',
    'app.tagline' => 'सुगम खरीद, पारदर्शी भुगतान',
    'app.language' => 'भाषा',

    'nav.home' => 'होम',
    'nav.dashboard' => 'डैशबोर्ड',
    'nav.bookings' => 'बुकिंग',
    'nav.queue' => 'कतार',
    'nav.procurement' => 'खरीद',
    'nav.payments' => 'भुगतान',
    'nav.profile' => 'प्रोफ़ाइल',
    'nav.settings' => 'सेटिंग्स',
    'nav.admin' => 'प्रशासन',
    'nav.logout' => 'लॉग आउट',

    'auth.login' => 'लॉगिन',
    'auth.register' => 'पंजीकरण',
    'auth.mobile' => 'मोबाइल नंबर',
    'auth.password' => 'पासवर्ड',
    'auth.otp' => 'ओटीपी',
    'auth.forgot_password' => 'पासवर्ड भूल गए?',
    'auth.reset_password' => 'पासवर्ड रीसेट करें',
    'auth.welcome_back' => 'फिर से स्वागत है',
    'auth.login_title' => 'अपने खाते में लॉगिन करें',

    'common.save' => 'सहेजें',
    'common.cancel' => 'रद्द करें',
    'common.confirm' => 'पुष्टि करें',
    'common.delete' => 'हटाएँ',
    'common.edit' => 'संपादित करें',
    'common.view' => 'देखें',
    'common.close' => 'बंद करें',
    'common.search' => 'खोजें',
    'common.submit' => 'जमा करें',
    'common.next' => 'आगे',
    'common.back' => 'पीछे',
    'common.ok' => 'ठीक है',
    'common.yes' => 'हाँ',
    'common.no' => 'नहीं',
    'common.actions' => 'कार्रवाई',
    'common.all' => 'सभी',
    'common.loading' => 'लोड हो रहा है...',
    'common.language' => 'भाषा',
    'common.none' => 'कोई नहीं',

    'booking.title' => 'स्लॉट बुक करें',
    'booking.book_slot' => 'स्लॉट बुक करें',
    'booking.slot' => 'स्लॉट',
    'booking.date' => 'तारीख',
    'booking.crops' => 'फ़सलें',
    'booking.cancel' => 'बुकिंग रद्द करें',
    'booking.confirm' => 'बुकिंग की पुष्टि करें',
    'booking.success' => 'आपका स्लॉट सफलतापूर्वक बुक हो गया',

    'queue.title' => 'लाइव कतार',
    'queue.position' => 'आपकी स्थिति',
    'queue.ahead' => 'आपसे आगे के किसान',
    'queue.status_called' => 'बुलाया गया',
    'queue.status_waiting' => 'प्रतीक्षा में',

    'procurement.title' => 'खरीद',
    'procurement.gross' => 'कुल वज़न',
    'procurement.deduction' => 'कटौती',
    'procurement.net' => 'शुद्ध वज़न',
    'procurement.rate' => 'दर',

    'payment.title' => 'भुगतान',
    'payment.amount' => 'राशि',
    'payment.status' => 'स्थिति',
    'payment.pending' => 'लंबित',
    'payment.paid' => 'भुगतान किया गया',

    'validation.required' => 'यह फ़ील्ड अनिवार्य है',
    'validation.invalid_mobile' => 'मान्य मोबाइल नंबर दर्ज करें',
    'validation.invalid_otp' => 'अमान्य या समाप्त ओटीपी',

    'errors.generic' => 'कुछ गलत हो गया',
    'errors.network' => 'कोई इंटरनेट कनेक्शन नहीं',
    'errors.forbidden' => 'आपके पास अनुमति नहीं है',
    'errors.not_found' => 'नहीं मिला',

    'dashboard.greeting' => 'नमस्ते',
    'dashboard.active_bookings' => 'सक्रिय बुकिंग',
    'dashboard.next_slot' => 'अगला बुकिंग स्लॉट',
    'dashboard.balance' => 'लंबित भुगतान',

    'settings.language' => 'भाषा',
    'settings.notification' => 'सूचनाएँ',
    'settings.change_password' => 'पासवर्ड बदलें',
    'settings.notifications_enabled' => 'सूचनाएँ सक्षम करें',

    'files.title' => 'फ़ाइलें',
    'files.upload' => 'अपलोड करें',
    'files.download' => 'डाउनलोड',
    'files.delete' => 'हटाएँ',
    'files.folder' => 'फ़ोल्डर',
    'files.size' => 'आकार',
    'files.type' => 'प्रकार',
    'files.uploaded_at' => 'अपलोड समय',
    'files.scope' => 'दायरा',
    'files.no_files' => 'कोई फ़ाइल नहीं मिली',
    'files.confirm_delete' => 'इस फ़ाइल को हमेशा के लिए हटाएँ?',
];